### ISSUE TITLE
FXServer won't start with txAdminLogs

### ISSUE THREAD

**Issue by NoobSpielt** [jhag01/txAdminLogs#2]
If I ensure txAdminLogs in my server.cfg txAdmin won't start and wants me to remove the ressource from my server.cfg . If I rename it to something without txadmin in its starts. 
Could it be that txAdmin blocks any ressource with txadmin in its name?
If yes you should consider renaming it.

txadmin: v4.14.1
FXServer: 5584
OS: Red Hat Enterprise Linux release 8.5 (Ootpa)

**Comment by jhag01** [comment]
I'm currently running it on v4.14.0 on 5562 and it works fine. I'll look into the issue regarding the new txAdmin update.

If there's no solution I'll change the readme.

Thank you for the heads up!
