### ISSUE TITLE
GetPlayerName(target) won't work on playerKicked and playerBanned

### ISSUE THREAD

**Issue by NoobSpielt** [jhag01/txAdminLogs#3]
I am not completely sure but i think that becouse the log event is only triggered after already kicking/banning the player (target) so the function GetPlayerName(target) can't work becouse the player (target) is not on the server anymore . With that is a Getplayername not working. 

Im not sure what a fix would be. But a quick fix is removing the GetPlayerName(target) from playerBanned and playerKicked

**Comment by jhag01** [comment]
Just pushed a temp fix, might be updating the resource to the newer txAdmin version if I have more time.
